language: python
cache: pip
sudo: required
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y gfortran
    - sudo apt-get install -y libatlas-dev liblapack-dev libblas-dev
before_script:
    - pip uninstall -y dulwich
    - pip install -e git@github.com:jelmer/dulwich.git
script:
    - pytest
    - python setup.py bdist_wheel
deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: dist/*.whl
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
  - provider: pypi
    user: bwanamarko
    password: $PYPI_PASSWORD
    distributions: "sdist bdist_wheel" # Your distributions here
    on:
      tags: true
